### ISSUE TITLE
Filestack for Angular

### ISSUE THREAD

**Issue by thinq4yourself** [emotivhq/gs-concierge#11]
## Option 1:

https://filepicker.github.io/filepicker-angular/demo/index.html
See `filestack` repo - already installed ;)
### But receives an error:

`injector:strictdi error on filepicker module`
...

```
Error: [$injector:strictdi] filepickerDirective is not using explicit annotation and cannot be invoked in strict mode
```
### Docs:

https://docs.angularjs.org/error/$injector/strictdi
## Option 2:

https://www.filestack.com/docs/support/integration/117

**Comment by yaboi** [comment]
`strictdi` and `$injector` errors are the same, or similar, error that we're receiving when we try to use the `embedlyServiceProvider` from our own module and not `bower_components`.

Just an observation..

**Comment by thinq4yourself** [comment]
Fixed for `embedlyServiceProvider` and merged in all repos ;)

Also fixed for filestack now.
