### ISSUE TITLE
Intercom popup shows on wrong side

### ISSUE THREAD

**Issue by yaboi** [emotivhq/gs-concierge#39]
Sometimes on load it will show automatically, but even on hover, the Intercom widget popover shows on the wrong side...

<img width="649" alt="screen shot 2016-05-27 at 12 15 39 pm" src="https://cloud.githubusercontent.com/assets/1933226/15614088/c4e07fc0-2404-11e6-9c97-94cd06d6273a.png">

It should pop up with a tooltip and mostly to the right, not left.

**Comment by thinq4yourself** [comment]
LOL, that's not a bug!! HA that's a feature!!!...to avoid it covering the `next` button on our Create widget. Also temporary...but nonetheless [is a feature](https://github.com/emotivhq/gs-concierge/blob/master/app/ui/custom.scss#L2)
